name: Deploy Ulang Tiap Jam

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "relaybot"
          heroku_email: "cepetinkredit@outlook.com"
